---
name: Metrics
on:
  # Schedule daily updates
  schedule: [cron: 0 0 * * *]
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Australia/Melbourne
          plugin_achievements: true
          plugin_achievements_display: detailed
          plugin_achievements_secrets: true
          plugin_achievements_threshold: C
          plugin_activity: true
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: true
          plugin_followup_sections: repositories

          plugin_habits: true
          plugin_habits_facts: true
          plugin_habits_charts: true

          plugin_languages: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: true

          plugin_people: true
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following

          plugin_repositories: true
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 100
